USE [master]
GO

/****** Object:  Database [DOCA_platform]    Script Date: 10/8/2023 10:34:33 AM ******/
CREATE DATABASE [DOCA_platform]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DOCA_platform', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\DOCA_platform.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DOCA_platform_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.SQLEXPRESS\MSSQL\DATA\DOCA_platform_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DOCA_platform].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DOCA_platform] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DOCA_platform] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DOCA_platform] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DOCA_platform] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DOCA_platform] SET ARITHABORT OFF 
GO

ALTER DATABASE [DOCA_platform] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DOCA_platform] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DOCA_platform] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DOCA_platform] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DOCA_platform] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DOCA_platform] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DOCA_platform] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DOCA_platform] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DOCA_platform] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DOCA_platform] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DOCA_platform] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DOCA_platform] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DOCA_platform] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DOCA_platform] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DOCA_platform] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DOCA_platform] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DOCA_platform] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DOCA_platform] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DOCA_platform] SET  MULTI_USER 
GO

ALTER DATABASE [DOCA_platform] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DOCA_platform] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DOCA_platform] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DOCA_platform] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DOCA_platform] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DOCA_platform] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [DOCA_platform] SET QUERY_STORE = ON
GO

ALTER DATABASE [DOCA_platform] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [DOCA_platform] SET  READ_WRITE 
GO


